{% set name = "sixelcrop" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sixelcrop-{{ version }}.tar.gz
  sha256: d6c05ac4fbd6e201f794aded12300fb427573172c0544a1fd25a48a66a5bc86f

build:
  entry_points:
    - sixelcrop = sixelcrop:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - sixelcrop
  commands:
    - pip check
    - sixelcrop --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sixelcrop/
  summary: A library for cropping sixel images
  dev_url: https://github.com/joouha/sixelcrop
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
